### ISSUE TITLE
Different result in GPU and CPU

### ISSUE THREAD

**Issue by yuanhn5206** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#18]
I encountered a strange problem. When I used CPU inference, the target detection results were normal, but when using GPU inference, the value of the rectangular box was always 0. The following picture is some output results.

CPU------------------------
15.4942
10.9904
28.4492
21.8784
1.05563e-06
7.57292e-06
5.72447e-06
9.91832e-07
1.85078e-06
1.1658e-05
1.65918e-06
6.30653e-06
6.4014e-07
1.87825e-05
4.37726e-05
1.48732e-06
5.1716e-07
6.61814e-06
3.76562e-06
5.7292e-06
2.79151e-06
8.98612e-06
6.7496e-06
1.34859e-05
27.2795
18.3552
47.5041
36.4909
1.28477e-05
8.72497e-05
8.37334e-05
2.93544e-06
0.00010424
0.000239199
8.42577e-05
8.20403e-05
3.92749e-05
0.0021232
0.00377457
1.47905e-05
1.82489e-05
0.000125664
0.000192699
0.000101505
2.09434e-05
0.000147003
0.00015937
0.000245364
32.9373
17.1653
54.0406
34.1962
2.88635e-05
0.000185051
0.000352726
3.86845e-06
9.93938e-05
0.000557964
8.13861e-05
0.000152232
2.74135e-05
0.00207775
0.00553999
2.82415e-05
9.67243e-06
0.000288354
0.000105202
0.0002281
5.08929e-05
0.000230567
0.000377558
0.000580006
34.3088
9.65056
56.38
19.1634
3.70653e-05
0.000154907
0.00033968
2.77421e-06
3.21735e-05
0.000230979
9.60374e-05
0.000251595
2.00272e-05
0.00288773
0.00344727
2.51078e-05
6.84874e-06
0.000232294
0.000118372
0.000387914
8.13358e-05
0.000362214
0.000203485
0.000643455
34.8979
6.66919
57.944
13.2521

----GPU----
0
0
0
0
1.05565e-06
7.57309e-06
5.72462e-06
9.91844e-07
1.85088e-06
1.16583e-05
1.65927e-06
6.30673e-06
6.40172e-07
1.87837e-05
4.37749e-05
1.48735e-06
5.17181e-07
6.61831e-06
3.76581e-06
5.72936e-06
2.79159e-06
8.9864e-06
6.74976e-06
1.34862e-05
0
0
0
0
1.28477e-05
8.72495e-05
8.37339e-05
2.93543e-06
0.000104239
0.000239198
8.42571e-05
8.20412e-05
3.92745e-05
0.00212321
0.00377459
1.47904e-05
1.82486e-05
0.000125664
0.000192698
0.000101506
2.09435e-05
0.000147004
0.00015937
0.000245366
0
0
0
0
2.88634e-05
0.000185051
0.000352728
3.86845e-06
9.93927e-05
0.000557965
8.13854e-05
0.000152233
2.74133e-05
0.00207776
0.00553999
2.82414e-05
9.67232e-06
0.000288354
0.000105201
0.0002281
5.08929e-05
0.000230567
0.00037756
0.000580011
0
0
0
0
3.70648e-05
0.000154906
0.000339678
2.77419e-06
3.21732e-05
0.000230977
9.60363e-05
0.000251594
2.00271e-05
0.00288773
0.00344728
2.51076e-05
6.84868e-06
0.000232292
0.000118372
0.000387911
8.1335e-05
0.000362212
0.000203484
0.000643453
0
0
0
0

My environment is：
VS2022+OPENCV4.8.1

hope you help me, it's really a great project

**Comment by yuanhn5206** [comment]
I print variable data 100

**Comment by JustasBart** [comment]
Hi @yuanhn5206 what you're describing sounds a lot like issue https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/issues/15. Are you able to try this with OpenCV 4.7.0 as outlined?

Let me know, all the best! 🚀

**Comment by yuanhn5206** [comment]
> Hi @yuanhn5206 what you're describing sounds a lot like issue #15. Are you able to try this with OpenCV 4.7.0 as outlined?
> 
> Let me know, all the best! 🚀

I will try opencv4.7, thank you for reply quickly

**Comment by yuanhn5206** [comment]
> Hi @yuanhn5206 what you're describing sounds a lot like issue #15. Are you able to try this with OpenCV 4.7.0 as outlined?
> 
> Let me know, all the best! 🚀

**I tried opencv 4.7 and it works in both gpu and cpu**, I also tried in opencv 4.9, it works in CPU but the same result in opencv4.8, the boxes are all 0.

**Comment by JustasBart** [comment]
@yuanhn5206 That's good to hear that you've got something sorted out and working!

I haven't been doing much research on this topic lately as I'm not working in the same field anymore but it would be rather curious to know what's changed since OpenCV 4.8.0 ...
Maybe by the time OpenCV 5.x is released I might revisit this and try and get it to work for that. The last few attempts at building OpenCV 4.9.0 resulted in the Eigen library not building properly (Ubuntu 20.04) which when disabled fails to build the AlphaMat which when disabled fails to build some NVidia CUDDN (Or some similar critical bit).

So it seems like for now the most straight forward way of getting this to run properly is to use OpenCV 4.7.0 which appears to just work.

I'll close the issue for now and leave a note on the description, thanks for the feedback and all the best! :rocket:

**Comment by yushijie94** [comment]
my god, i tried a million things, but now i think this will help!
